version: "3.8"

services:
###Iniciar página: http://localhost:8880/otrs/index.pl
###Usuário: root@localhost
###Senha: GVYskvEXNPxLcu4V
  znuny:
    #build: ./docker/
    image: docker-znuny-rel-7_0_19-znuny
    restart: always
    #container_name: znuny
    ports:
      - 8380:8880
      - 8381:8881
    env_file: .env      
    volumes:
      - ./init:/app
      - ./app:/opt/znuny
    depends_on:
      - db
    networks: 
      - otrs      
  db:
    image: mariadb:10.11.3
    restart: always
    environment:
      MARIADB_USER: otrs
      MARIADB_PASSWORD: jurema
      MARIADB_DATABASE: otrs
      MARIADB_ROOT_PASSWORD: jurema
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db/conf/50-znuny_config.cnf:/etc/mysql/mariadb.conf.d/50-znuny_config.cnf
    networks: 
      - otrs
networks:
  otrs:
    driver: bridge